version: '3'

services:
  backend:
    build: ./blog-backend
    ports:
      - "3001:3001"
    environment:
      NEO4J_URI: "neo4j://neo4j:7687"
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: Daylights#123
    command: sh -c "wait-for-it.sh neo4j:7687 -t 60 && node index.js" # Using wait-for-it script
    restart: on-failure
    depends_on:
      neo4j:
        condition: service_healthy # Waits until the Neo4j service is healthy

  neo4j:
    build: ./neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "neo4j/Daylights#123"
      
  frontend:
    build: ./blog-ui
    ports:
      - "4000:3000" # Change the port if needed
