apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: blog-ui:latest
          ports:
            - containerPort: 3000
          # Add other configurations or volumes if needed

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: blog-backend:latest
          ports:
            - containerPort: 3001
          env:
            - name: NEO4J_URI
              value: "neo4j://neo4j:7687"
            - name: NEO4J_USER
              value: neo4j
            - name: NEO4J_PASSWORD
              value: Daylights#123
          # Add other configurations or volumes if needed

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
        - name: neo4j
          image: neo4j:latest
          ports:
            - containerPort: 7474
            - containerPort: 7687
          env:  # Define environment variables here
            - name: NEO4J_AUTH
              value: "neo4j/Daylights#123"
          # Add other configurations or volumes if needed

